# Generated by Django 4.2.11 on 2024-05-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year_Built', models.IntegerField()),
                ('Total_Bsmt_SF', models.IntegerField()),
                ('first_Flr_SF', models.IntegerField()),
                ('Gr_Liv_Area', models.IntegerField()),
                ('Garage_Area', models.IntegerField()),
                ('Overall_Qual', models.IntegerField()),
                ('Full_Bath', models.IntegerField()),
                ('Exter_Qual', models.CharField(max_length=10)),
                ('Kitchen_Qual', models.CharField(max_length=10)),
                ('Neighborhood', models.CharField(max_length=50)),
            ],
        ),
    ]
